# Generated by Django 4.0.6 on 2022-07-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubWithTeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='use_teachers', to='account.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='my_subjects', to='account.teacher', verbose_name='Учитель')),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(related_name='use_grades', to='account.subwithteach', verbose_name='Предметы'),
        ),
    ]
