SECRET_KEY = 'django-insecure-=#b!%xkhb(qi(-7dlrts*$x&pql3=7h^%ju8w_oxm5i(gx*3zz'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_HOST_USER = 'school-mektep@mail.ru'
EMAIL_HOST_PASSWORD = 'RdcCBks50dUgFDc0Hcl9'
ADMIN_URL = 'admin/'