# Generated by Django 4.0.6 on 2022-07-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_diary', to='account.student', verbose_name='Ученик(ца)')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(help_text='от 1 до 8', verbose_name='День недели')),
                ('start_lesson', models.TimeField(verbose_name='Начало урока')),
                ('finish_lesson', models.TimeField(verbose_name='Конец урока')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_timetables', to='account.grade', verbose_name='Класс')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='account.school', verbose_name='Школа')),
                ('subject', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_timetable', to='account.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='my_timetables', to='account.teacher', verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_quarter', models.PositiveSmallIntegerField(help_text='Цифрами', verbose_name='Какой четверть')),
                ('mark', models.PositiveSmallIntegerField(blank=1, null=1, verbose_name='Оценка')),
                ('set_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='subject.diary', verbose_name='Дневник')),
                ('student', models.ForeignKey(help_text='Ученик', on_delete=django.db.models.deletion.CASCADE, related_name='my_quarters', to='account.student', verbose_name='Кому')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='my_set_quarter', to='account.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Четверть',
                'verbose_name_plural': 'Четверти',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(blank=1, null=1, verbose_name='Оценка')),
                ('why', models.CharField(blank=1, help_text='Необязательно', max_length=255, null=1, verbose_name='За что')),
                ('set_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='subject.diary', verbose_name='Дневник')),
                ('student', models.ForeignKey(help_text='Ученик', on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Кому')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher', verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_course', models.TimeField(verbose_name='Начало курса')),
                ('finish_course', models.TimeField(verbose_name='Конец курса')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=1, help_text='Необязательно', null=1, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=1, help_text='Необязательно', null=1, verbose_name='Цена')),
                ('weekdays', models.CharField(default='123', help_text='от 1 до 8', max_length=7, verbose_name='Какие дни будут')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_course', to='account.school', verbose_name='Школа')),
                ('students', models.ManyToManyField(blank=1, related_name='my_course', to='account.student', verbose_name='Ученики')),
                ('teacher', models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='my_course', to='account.teacher', verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
