# Generated by Django 4.0.6 on 2022-07-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_quarter', models.PositiveSmallIntegerField(help_text='Цифрами', verbose_name='Какой четверть')),
                ('mark', models.PositiveSmallIntegerField(blank=1, null=1, verbose_name='Оценка')),
                ('set_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('student', models.ForeignKey(help_text='Ученик', on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Кому')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(blank=1, null=1, verbose_name='Оценка')),
                ('set_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('student', models.ForeignKey(help_text='Ученик', on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Кому')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher', verbose_name='Преподователь')),
            ],
        ),
    ]
